-- INSERT INTO users (username, email, password) VALUES
--                                              ('Lokesh', 'abc@gmail.com', 'pass1234'),
--                                              ('Deja', 'xyz@email.com', 'pass2345'),
--                                              ('Caption', 'cap@marvel.com', 'pass3456');
--
-- INSERT INTO roles (name) VALUES
--                                                   ('ROLE_USER'),
--                                                   ('ROLE_MODERATOR'),
--                                                   ('ROLE_ADMIN');
--
